#!/usr/bin/python
from hawkAPI.lib.core.hawkcore import hawkcore
from hawkAPI.lib.core.hawkapi import hawkapi
from hawkAPI.lib.core.hawklib import hawklib
from hawkAPI.lib.plugins.hawkCSV import hawkCSV
from operator import itemgetter
import inspect
import sys
import argparse


#usage = 'failedattemptsCSV -u "id" -p "pass" -i "server" -c "client" -s start -e end -d directory -t type'
usage = "Created By Dan Felts"
parser = argparse.ArgumentParser(description="Get failed attempt logins by group",epilog=usage)
parser.add_argument("-u","--user",help="Username",type=str,required=True)
parser.add_argument("-p","--passw",help="Password",type=str,required=True)
parser.add_argument("-i","--server",help="The hawk server IP",type=str,required=True)
parser.add_argument("-c","--client",help="The client name",type=str,required=True)
parser.add_argument("-d","--dir",help="location to store",type=str,required=True)
parser.add_argument("-s","--start",help="Start Date",type=str,required=True)
parser.add_argument("-e","--end",help="End Date",type=str,required=True)
parser.add_argument("-db","--debug",help="Set Debug on",action="store_true",required=False)
parser.add_argument("-l","--limit",help="Set Limit of return",type=int,required=False)

if len(sys.argv) < 7:
    parser.print_help()
    sys.exit()

opt = parser.parse_args()
hawk = hawkcore(opt.server)
hawk.login(opt.user,opt.passw)
res = hawkapi(hawk)
lib = hawklib(hawk)

if opt.limit:
       data = res.getFailedLoginsByGroup(lib.conDateToUtc(opt.start),lib.conDateToUtc(opt.end),opt.client,tp="login",lm=opt.limit)
else:
    dates = lib.getDates(lib.conDateToUtc(opt.start),lib.conDateToUtc(opt.end))
    data = []
    for i in dates:
        start,end,idit = i
        print "%s:%s --- %s" % (start,end,idit)
        f = res.getFailedLoginsByGroup(start,end,opt.client,tp="login")
        if not f:
          pass
        else:
          for i in f:
              c.append(i)
c.sort(key=itemgetter('date_added'))
csv = hawkCSV("%s/%s.csv" % (opt.dir,opt.client),hawk)
csv.build(c)
hawk.logout()
